[package]
name = "tensorscript"
version = "0.1.0"
authors = ["ricky han <rickylqhan@gmail.com>"]

[dependencies]
pest = "^1.0.0-beta"
pest_derive = "^1.0.0-beta"
maplit = "1.0.1"
codespan = "0.1.1"
codespan-reporting = "0.1.3"
